version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: consulta_cep_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock:2.32.0
    container_name: wiremock
    ports:
      - "8081:8081"
    volumes:
      - ./wiremock:/home/wiremock

volumes:
  postgres_data: