services:
  postgres:
    image: postgres:16.6
    container_name: postgres
    environment:
      POSTGRES_DB: consulta_cep_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock:3.10.0-1
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock

volumes:
  postgres_data: